CREATE DATABASE url_db;

CREATE TABLE url_db.funding_opportunity_urls(
	id int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    url varchar(500) NOT NULL,
	closeDate DATE NOT NULL,
	UNIQUE (url)
);

CREATE TABLE url_db.archived_links(
	id int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    url varchar(500) NOT NULL,
	closeDate DATE,
    reason varchar(500),
	UNIQUE (url)
);

INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://cytokinesociety.org/about-us/honorary-members/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.rwjf.org/en/grants/active-funding-opportunities/2024/harold-amos-medical-faculty-development-program.html', '2024-03-19');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.rwjf.org/en/grants/active-funding-opportunities/2020/pioneering-ideas-submission.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.rwjf.org/en/grants/active-funding-opportunities/2024/healthy-eating-research.html', '2024-04-03');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.rwjf.org/en/grants/active-funding-opportunities/2024/evidence-for-action--innovative-research-to-advance-racial-equity.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.rwjf.org/en/grants/active-funding-opportunities/2024/health-policy-research-scholars.html', '2024-03-07');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grantcenter.jdrf.org/rfa/industry-discovery-development-partnerships/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grantcenter.jdrf.org/rfa/innovative-awards/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grantcenter.jdrf.org/rfa/career-development-awards/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ms-fund.keio.ac.jp/en/prize/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://nam.edu/gustav-o-lienhard-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.loreal.com/en/usa/pages/group/fwis/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.lupus.org/career-development-for-researchers/evelyn-v-hess-md-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.lupusresearch.org/for-researchers/funding-opportunities/#collapse101', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://fnih.org/our-programs/powering-science/the-lurie-prize-in-biomedical-sciences/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.lymphoma.org/researchers/rfp/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aaas.org/programs/marion-milligan-mason-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.nasonline.org/programs/awards/kovalenko-medal.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://rarediseases.org/advancing-research/research-grant-programs/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://rarediseases.org/advancing-research/request-for-proposals/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.psoriasis.org/bridge-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.psoriasis.org/discovery-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.psoriasis.org/early-career-research-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.psoriasis.org/mental-health-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.psoriasis.org/translational-research-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.science.org/content/page/nomis-science-young-explorer-award', '2024-05-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://molmed.biomedcentral.com/about/rossprize', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.sdbonline.org/sdb_emerging_research_organisms_grant', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.socmucimm.org/resources/grants-awards-funding/technique-sharing-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.socmucimm.org/resources/grants-awards-funding/travel-awards/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://stiresearch.health.pitt.edu/awards/thomas-e-starzl-prize-in-surgery-and-immunology/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://vilcek.org/prizes/vilcek-prizes-for-creative-promise/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.jnj.com/wistem2d-university-scholars', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aajr.org/funding-opportunities/baron-book-prize/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aajr.org/funding-opportunities/dissertation-research-funding/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aallnet.org/education-training/grants/research-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aamds.org/professionals/fund-your-research', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.baal.org.uk/what-we-do/funding/baal-applied-linguistics-fund/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.baal.org.uk/what-we-do/annual-conference/conference-scholarships/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://baas.ac.uk/funding/baas-development-fund/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://baas.ac.uk/funding/baas-us-embassy-small-grants-programme/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bacr.org.uk/awards-/bacr-hamilton-fairley-poster-prize', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bacr.org.uk/awards-/bacr-astrazeneca-young-scientist-frank-rose-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bacr.org.uk/awards-/the-bacr-student-impact-award', '9999-01-01');

INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bacr.org.uk/bursaries/bacr-student-awards', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bacr.org.uk/bursaries/non-student-travel-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bacr.org.uk/bursaries/travel-exchange', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bacr.org.uk/bursaries/mid-career-fellowship', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://bacsuk.org.uk/ecr-prize', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://bacsuk.org.uk/2020-uccl-funding', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://bacsuk.org.uk/2024-bacs-prize-for-best-doctoral-thesis-on-china', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ukri.org/opportunity/experimental-medicine/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ukri.org/opportunity/infections-and-immunity-research/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ukri.org/opportunity/clinical-research-training-fellowship/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ukri.org/opportunity/career-development-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.nihr.ac.uk/funding/nihr-development-and-skills-enhancement-award-dse/33250?utm_source=NIHR+mailing+list&utm_campaign=a78278b5a8-EMAIL_CAMPAIGN_2022_04_01_10_42_COPY_01&utm_medium=email&utm_term=0_570d86f9cb-a78278b5a8-33316359', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.baderc.org/pilot-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://baef.be/alumni-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bafound.org/apply-for-a-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bankofcanada.ca/research/research-paper-awards/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bankofcanada.ca/careers/scholarship-awards/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bantingresearchfoundation.ca/discovery-award-program/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bap.org.uk/awardinfo.php?awardinfoID=2', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bap.org.uk/awardinfo.php?awardinfoID=8', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bap.org.uk/awardinfo.php?awardinfoID=7', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bap.org.uk/awardinfo.php?awardinfoID=10', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bap.org.uk/awardinfo.php?awardinfoID=15', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bard-isus.com/fundingTypes/Details/23', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bard-isus.com/fundingTypes/Details/18', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bard-isus.com/fundingTypes/Details/1', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bard-isus.com/fundingTypes/Details/24', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.bard-isus.com/fundingTypes/Details/22', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.barrafoundation.org/grants/catalyst-fund/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.barrycf.org/grant/bcf-community-grant/', '2024-10-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.barrycf.org/grant/wilson-h-craig-jr/', '2024-04-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.barrycf.org/grant/youth-advisory-council-yac/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.barrycf.org/grant/delton-kellogg-education-foundation-dkef/', '2024-03-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.barrycf.org/grant/thornapple-area-enrichment-foundation-taef/', '2024-04-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.barrycf.org/grant/barry-health-access/', '2024-05-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.barrycf.org/grant/general-federation-of-womens-club/', '2024-06-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.barrycf.org/grant/barry-county-bar-association-community-improvement/', '2024-06-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.barrycf.org/grant/belonging-in-barry/', '2024-07-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ncsbn.org/public-files/Guidelines_for_Proposals.pdf', '2024-08-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://seagrant.noaa.gov/wp-content/uploads/2024/03/NOAA-OAR-SG-2024-25871.pdf', '2024-09-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://seagrant.noaa.gov/wp-content/uploads/2024/03/NOAA-OAR-SG-2024-25758.pdf', '2024-10-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/grants/aacr-ocular-melanoma-foundation-fellowship/', '2024-11-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/grants/aacr-ocular-melanoma/', '2024-12-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/grants/aacr-exelixis-rcc-fellowship/', '2025-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/grants/aacr-kidneycan-kidney-cancer-grant/', '2025-02-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/grants/aacr-lobular-carcinoma-innovation-and-discovery-grants/', '2025-03-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/grants/aacr-cancer-disparities-research-fellowships-aacr-grants/', '2025-04-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/grants/victorias-secret-global-fund-for-womens-cancers-career-development-award-in-partnership-with-pelotonia-and-aacr/', '2025-06-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/grants/triple-negative-breast-cancer-research-foundation-aacr-nextgen-grants-for-transformative-cancer-research/', '2025-07-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.nebf.org/gettingstarted', '2025-08-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://oac.ohio.gov/grants/10-grant-opportunities/01-sustainability', '2025-09-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://oac.ohio.gov/grants/10-grant-opportunities/65-statewide-arts-service-organizations', '2025-10-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://oac.ohio.gov/grants/10-grant-opportunities/10-artstart', '2025-11-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://oac.ohio.gov/grants/10-grant-opportunities/15-artsnext', '2025-12-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://oac.ohio.gov/grants/10-grant-opportunities/35-artsrise', '2026-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://oac.ohio.gov/grants/10-grant-opportunities/45-capacity-building', '2026-02-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://oac.ohio.gov/grants/10-grant-opportunities/70-ohio-artists-on-tour', '2026-03-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://oac.ohio.gov/grants/10-grant-opportunities/20-arts-partnership', '2026-04-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://oac.ohio.gov/grants/10-grant-opportunities/25-teachartsohio', '2026-05-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://oac.ohio.gov/grants/10-grant-opportunities/55-big-yellow-school-bus', '2026-06-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.nih.gov/grants/guide/pa-files/PAR-24-070.html', '2026-07-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.nih.gov/grants/guide/rfa-files/RFA-AT-24-008.html', '2026-08-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.nih.gov/grants/guide/rfa-files/RFA-OD-24-013.html', '2026-09-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.nih.gov/grants/guide/pa-files/PAR-23-318.html', '2026-11-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.nih.gov/grants/guide/pa-files/PAR-24-053.html', '2026-12-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.nih.gov/grants/guide/notice-files/NOT-OD-22-202.html', '2027-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/independent-research-grants/stand-up-to-cancer-dream-team-and-research-team-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/independent-research-grants/su2c-sharp-awards/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/grants/aacr-clinical-oncology-research-core-training-fellowships/', '2024-02-29');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/grants/aacr-gertrude-b-elion-cancer-research-award-2/', '2024-06-03');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/career-development-awards/aacr-career-development-awards-in-lung-cancer-research/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/career-development-awards/aacr-astrazeneca-career-development-award-for-physician-scientists-in-honor-of-jose-baselga/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/career-development-awards/aacr-debbies-dream-foundation-career-development-award-for-gastric-cancer-research/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/career-development-awards/aacr-mpm-oncology-charitable-foundation-transformative-cancer-research-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/career-development-awards/aacr-novocure-cda-for-tumor-treating-fields-research/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/career-development-awards/aacr-ocular-melanoma-foundation-cda/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/career-development-awards/aacr-st-baldricks-foundation-pediatric-cancer-research-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/career-development-awards/beginning-investigator-grant-for-catalytic-research-big-cat/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/career-development-awards/bcrf-aacr-cda-to-promote-diversity-and-inclusion/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/career-development-awards/lustgarten-foundation-aacr-cdas-for-pancreatic-cancer-research/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/kelly', '2024-06-30');


INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/livingood', '2024-01-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/development-advocacy-grant', '2024-09-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/established-advocacy-grant', '2024-09-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/fox', '2024-06-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/idea', '2024-09-04');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/travel', '2024-10-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/kenney', '2024-06-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/gruber', '2024-01-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/sulzberger-lecture', '2024-01-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/resident-improvement', '2024-08-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/developing-countries', '2024-07-31');

INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/strauss-katz', '2024-09-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/sulzberger-institute', '2024-09-04');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/young-investigator', '2024-09-01');

INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aad.org/member/career/awards/world-congress', '2024-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.iadr.org/awards/iadriap-ricardo-teles-clinical-research-award', '2024-03-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aadocr.org/awards/mind/aadocr-mind-future-mentee-application?_gl=1*47l9d2*_ga*MTA4MTIwNTMyNi4xNzA5NTg3NDU5*_ga_1LRD8JH5EM*MTcwOTU4NzQ1OC4xLjEuMTcwOTU4NzU1OS4wLjAuMA..*_ga_DG1MMR0V3P*MTcwOTU4NzQ1OC4xLjEuMTcwOTU4NzU1OS4wLjAuMA..*_ga_L1QNB8JRES*MTcwOTU4NzQ1OC4xLjEuMTcwOTU4NzU1OS4wLjAuMA..', '2024-05-10');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aadprt.org/annual-meeting/awards-fellowships/bell-faculty-fellowship-award', '2024-09-14');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aadprt.org/annual-meeting/awards-fellowships/award-detail?awardsid=82', '2024-09-14');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aadprt.org/annual-meeting/awards-fellowships/award-detail?awardsid=86', '2024-09-14');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aae.org/specialty/member-center/awards-recognition/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aaes.auburn.edu/grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.gov/search-results-detail/351948', '2024-06-19');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.gov/search-results-detail/351794', '2024-06-20');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.gov/search-results-detail/349806', '2024-05-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.grants.gov/search-results-detail/344227', '2024-06-20');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.grants.gov/search-results-detail/344228', '2024-06-20');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.gov/search-results-detail/349758', '2024-05-19');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.gov/search-results-detail/349840', '2024-05-10');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.gov/search-results-detail/352485', '2024-04-26');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.gov/search-results-detail/350060', '2024-06-20');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://grants.gov/search-results-detail/349743', '2024-05-23');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.grants.gov/search-results-detail/351880', '2024-06-03');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafpfoundation.org/grants-awards/chfm-student-and-resident-essay-contest.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafpfoundation.org/grants-awards/disaster-assistance-program.html', '9999-01-01');

INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafpfoundation.org/grants-awards/family-medicine-cares-resident-service-award.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafpfoundation.org/grants-awards/family-medicine-cares-usa/application-details.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafpfoundation.org/grants-awards/family-medicine-discovers-rapsdi.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafpfoundation.org/grants-awards/Family-Medicine-Leads-Emerging-Leader-Institute-Application.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafpfoundation.org/grants-awards/family-medicine-philanthropic-consortium-grants-program.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafpfoundation.org/grants-awards/family-medicine-philanthropic-consortium-chapter-engagement.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafpfoundation.org/grants-awards/student-externship-matching-grants.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafpfoundation.org/grants-awards/chfm-oral-history-grant.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafpfoundation.org/grants-awards/sandra-l-panther-fellowship.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafprs.org/Consumers/Foundation/AAFPRS_Awards/ERF/AAFPRS_Awards.aspx?hkey=26e3b691-12f7-4346-9a73-ce1a14f9c0d6', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafprs.org/ERF/LBG.aspx', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafprs.org/ERF/IDG.aspx', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aafprs.org/ERF/RRG.aspx', '9999-01-01');

INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aag.asn.au/Web/About-Us/Divisions/division-listing-act.aspx', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aag.asn.au/Web/About-Us/Divisions/division-listing-nt.aspx', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aag.org/award-grant/jackson_prize/', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/meridian_book/', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/globe_book/', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/diversityaward/', '2024-09-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/nystrom/', '2024-09-22');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/publication/', '2024-09-29');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/aag-honors/', '2024-09-29');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/aag-media-achievement-award/', '2024-09-29');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/programexcellence/', '2024-09-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/william-l-garrison-award-for-best-dissertation-in-computational-geography/', '2024-10-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/miller/', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/de-blij/', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/presidential-achievement/', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/laws/', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/wilbanks_award_for_transformational_research/', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/marcus/', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.instrumentl.com/grants/visiting-geographical-scientist-program/', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/geography-entrepreneurship-awards/', '2024-11-05');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/research/', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/grant-dissertation-research/', '2024-12-31');

INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aag.org/award-grant/anne_white_fund/', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aahn.org/research-awards', '2024-06-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aahn.org/research-grants', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://aahpm.org/about/awards', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.afar.org/grants/beeson', '2023-10-20');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aai.org/Careers/Fellowships/CIFP', '2024-03-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aai.org/Careers/Fellowships/Reentry', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aai.org/Careers/Fellowships/Intersect', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aaalac.org/awards/fellowship-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.lung.org/research/awards-and-grants-opportunities', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.autismspeaks.org/scientific-research-grants-and-fellowship-programs', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.cirm.ca.gov/about-cirm/funding-opportunities-discovery-stage-research/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.cirm.ca.gov/about-cirm/funding-opportunities-translational-research/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.cirm.ca.gov/researchers/funding-opportunities/clinical-trial-stage-projects/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.cirm.ca.gov/education-conference-grants-and-research-training-awards/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.cirm.ca.gov/researchers/funding-opportunities/infrastructure/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.gairdner.org/award/canada-gairdner-international-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.gairdner.org/award/john-dirks-canada-gairdner-global-health-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.gairdner.org/award/canada-gairdner-momentum-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.einsteinfoundation.de/en/award/', '2024-04-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://probioticsresearch.com/grant-program/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.crohnscolitisfoundation.org/research/grants-fellowships/entrepreneurial-investing', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://cytokinesociety.org/icis-pfizer-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://cytokinesociety.org/icis-biolegend-william-e-paul-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://cytokinesociety.org/luminex-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://cytokinesociety.org/icis-mentorship-award/', '9999-01-01');

INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.einsteinfoundation.de/en/funding/einstein-professorship', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://ekct.org.uk/grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ekfs.de/en/scientific-funding/funding-lines/first-and-second-applications', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://elasmo.org/awards-and-funding/early-career-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.eldp.net/en/our+grants/apply/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.elizabethgreenshieldsfoundation.org/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://elpnet.org/programs/ray-fellowship-program', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.embo.org/funding/fellowships-grants-and-career-support/scientific-exchange-grants/eligibility/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.embo.org/funding/fellowships-grants-and-career-support/advanced-collaboration-grants/eligibility/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.embo.org/funding/fellowships-grants-and-career-support/installation-grants/eligibility/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ena.org/about/awards-recognition/lantern', '2024-02-28');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.encephalitis.info/grants-available/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.endocrine.org/awards/eugenia-rosemberg-abstract-travel-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.endocrine.org/awards/mara-e-lieberman-memorial-travel-grants', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.endocrine.org/awards/early-investigators-awards', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.endocrine.org/awards/the-endocrine-society-outstanding-abstract-awards', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.endocrinesociety.org.au/awards-research-grants.asp', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.endocrinesurgery.org/society-grants-logerfo-and-thyca', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.endocrinology.org/grants-and-awards/grants/research-grant/', '2024-10-02');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.endocrinology.org/grants-and-awards/grants/meeting-learning-travel-grant/', '2024-10-02');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.endocrinology.org/grants-and-awards/grants/teaching-grant/', '2024-10-02');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.endocrinology.org/grants-and-awards/grants/outreach-grant/', '2024-10-02');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://endowment.org/grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://english.hi.is/research/the_ui_doctoral_grants_fund', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://english.hi.is/research/the_university_of_iceland_research_fund_0', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://english.hi.is/research/the_uis_research_fund_travel_grants', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.environment.nsw.gov.au/topics/heritage/heritage-grants', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.environment.nsw.gov.au/topics/water/coasts/coastal-and-estuary-grants', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.environment.nsw.gov.au/topics/water/floodplains/floodplain-management-grants', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.environment.nsw.gov.au/funding-and-support/nsw-environmental-trust/grants-available/clean-technology-research-and-development', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.environment.nsw.gov.au/funding-and-support/nsw-environmental-trust/grants-available/community-recycling-centres', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.environment.nsw.gov.au/funding-and-support/nsw-environmental-trust/closed-programs/emergency-pollution-cleanup', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.environment.nsw.gov.au/funding-and-support/nsw-environmental-trust/grants-available/environmental-research', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.environment.nsw.gov.au/funding-and-support/nsw-environmental-trust/grants-available/landfill-consolidation-and-environmental-improvements', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.epilepsy.ca/current-rfps-2024', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://epilepsy-institute.org.uk/eri/research/apply-for-funding/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://eppleyfoundation.org/#apply', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://eps.ac.uk/study-visit-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.eralberta.ca/funding-technology/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://erefdn.org/research-grants-projects/how-to-apply-for-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ersnet.org/science-and-research/clinical-research-collaboration-application-programme/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://esbiomech.org/es-awards/esb-clinical-biomechanics-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://esbiomech.org/es-awards/the-s-m-perren-research-award-2/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://erc.europa.eu/apply-grant/starting-grant', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://erc.europa.eu/apply-grant/consolidator-grant', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://erc.europa.eu/apply-grant/advanced-grant', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.eso.net/en/what%2dwe%2ddo/eso%2dfinancial%2daid/1-5039-1-', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.esperantic.org/en/grants/available/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=30', '2024-09-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=31', '2024-09-30');

INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=32', '2024-09-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=24', '2024-10-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=25', '2024-12-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=28', '2024-10-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=29', '2024-12-20');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=6', '2024-10-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=15', '2024-10-29');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=4', '2024-06-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=5', '2024-10-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=9', '2024-06-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=10', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=16', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=17', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espid.org/award-details.aspx?group=awards&id=26', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espr.eu/funding/roland_r_wauer_award.php', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espr.eu/funding/bengt_robertson_award.php', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.espr.eu/funding/early_career_investigator_awards.php', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://esprentissfoundation.org/grant-application', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ukri.org/opportunity/access-to-high-performance-computing-facilities-2024/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ukri.org/opportunity/design-exchange-partnerships-design-the-green-transition-round-3/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ukri.org/opportunity/net-zero-digital-research-infrastructure-coordinator-and-network/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ukri.org/opportunity/accelerating-the-green-economy-centres/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ukri.org/opportunity/smart-data-research-uk-data-services/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.ukri.org/opportunity/epsrc-uk-catalysis-hub-phase-iii/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.esu.org/awards/international-oracy-teacher-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.esu.org/awards/oracy-culture-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://ethnobiology.org/awards/barbara-lawrence-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://euraxess.ec.europa.eu/jobs/funding/cris-excellence-programme', '2024-05-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://euraxess.ec.europa.eu/jobs/funding/c-ris-emerging-leader-programme', '2024-05-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://euraxess.ec.europa.eu/jobs/funding/cris-translational-physician-talent-programme', '2024-05-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://nrc.canada.ca/en/support-technology-innovation/eureka', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.eurospe.org/grants-awards/grants/early-career-scientific-development-grant/', '2024-05-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.evancornishfoundation.org.uk/how-to-apply#overseas', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://everycat.org/the-latest/grants/grant-process/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://euroqol.org/research-at-euroqol/funding-rounds/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://eyesightfoundation.org/how-to-apply/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://faa.illinois.edu/research/research-funding-resources/lorado-taft-lectureship-on-art/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://faa.illinois.edu/research/research-funding-resources/kate-neal-kinley-memorial-fellowship/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://faa.illinois.edu/research/research-funding-resources/college-sponsored-funding/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://albertinefoundation.org/albertine-grants/jazz-new-music/creative-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://albertinefoundation.org/albertine-grants/jazz-new-music/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://albertinefoundation.org/albertine-grants/french-immersion/eligibility-guidelines/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.australiajapaninnovation.org/grants-program', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.familyprocess.org/grants-initiative/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.fanconi.org/explore/apply-for-grant-funding', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.faseb.org/awards/excellence-in-science', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://fawc.org/apply/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://fellowshipsfund.com.au/fellowships/#eligibility', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://fems-microbiology.org/about_fems/network-and-activities/grants/fems-research-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://fems-microbiology.org/about_fems/network-and-activities/grants/industry-placement-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.fic.nih.gov/Grants/Pages/Apply.aspx', '9999-01-01');

INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aaaai.org/professional-education/grants-awards', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aaas.org/awards/science-diplomacy/about?adobe_mc=MCMID%3D61683648326968651550209216694848071726%7CMCORGID%3D242B6472541199F70A4C98A6%2540AdobeOrg%7CTS%3D1709529400', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aaas.org/awards/scientific-freedom-and-responsibility/about?adobe_mc=MCMID%3D61683648326968651550209216694848071726%7CMCORGID%3D242B6472541199F70A4C98A6%2540AdobeOrg%7CTS%3D1709529400', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aaas.org/awards/early-career-public-engagement/about?adobe_mc=MCMID%3D61683648326968651550209216694848071726%7CMCORGID%3D242B6472541199F70A4C98A6%2540AdobeOrg%7CTS%3D1709529400', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aaas.org/awards/john-mcgovern-lecture?adobe_mc=MCMID%3D61683648326968651550209216694848071726%7CMCORGID%3D242B6472541199F70A4C98A6%2540AdobeOrg%7CTS%3D1709529583', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aaas.org/awards/mentor/about?adobe_mc=MCMID%3D61683648326968651550209216694848071726%7CMCORGID%3D242B6472541199F70A4C98A6%2540AdobeOrg%7CTS%3D1709529583', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aaas.org/awards/newcomb-cleveland-prize/about?adobe_mc=MCMID%3D61683648326968651550209216694848071726%7CMCORGID%3D242B6472541199F70A4C98A6%2540AdobeOrg%7CTS%3D1709529583', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aaas.org/awards/philip-hauge-abelson/about?adobe_mc=MCMID%3D61683648326968651550209216694848071726%7CMCORGID%3D242B6472541199F70A4C98A6%2540AdobeOrg%7CTS%3D1709529583', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aaas.org/awards/aaas-subaru-sbf-prize-excellence-science-books/about?adobe_mc=MCMID%3D61683648326968651550209216694848071726%7CMCORGID%3D242B6472541199F70A4C98A6%2540AdobeOrg%7CTS%3D1709529583', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aaas.org/fellowships/loreal-usa-women?adobe_mc=MCMID%3D61683648326968651550209216694848071726%7CMCORGID%3D242B6472541199F70A4C98A6%2540AdobeOrg%7CTS%3D1709529646', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aab.org.uk/conferences/aab-carer-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aabb.org/get-involved/awards/aabb-memorial-awards/bernard-fantus-lifetime-achievement-medal', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aabb.org/get-involved/awards/aabb-memorial-awards/dale-a-smith-memorial-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aabb.org/get-involved/awards/aabb-memorial-awards/emily-cooley-memorial-award-and-lectureship', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aabb.org/get-involved/awards/aabb-memorial-awards/hemphill-jordan-leadership-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aabb.org/get-involved/awards/aabb-memorial-awards/john-elliott-memorial-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aabb.org/get-involved/awards/aabb-memorial-awards/landsteiner-alter-award-and-lectureship', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aabb.org/get-involved/awards/aabb-memorial-awards/sally-frank-memorial-award-and-lectureship', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aabb.org/get-involved/awards/aabb-memorial-awards/tibor-greenwalt-memorial-award-and-lectureship', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aabb.org/foundation/foundation-award-for-innovative-research', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aabb.org/get-involved/awards/rise-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aabb.org/get-involved/awards/future-leader-scholarship-awards-program', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aabs-balticstudies.org/grants-fellowships/aabs-book-publication-subvention/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aabs-balticstudies.org/grants-fellowships/emerging/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aabs-balticstudies.org/grants-fellowships/birnitis/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aabs-balticstudies.org/grants-fellowships/saltups/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aabs-balticstudies.org/grants-fellowships/grundmanis/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aabs-balticstudies.org/grants-fellowships/dissertation/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aabs-balticstudies.org/grants-fellowships/baumanis/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aabs-balticstudies.org/awards-prizes/undergraduate-paper-in-baltic-studies-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aabs-balticstudies.org/awards-prizes/aabs-book-prize/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://aabs-balticstudies.org/awards-prizes/vilis-vitols-article-prize/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.myadlm.org/science-and-research/research-grants/general-research-grant', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.myadlm.org/science-and-research/research-grants/cpoct-research-grant', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacom.org/medical-education/grants-fellowships/aacom-research-grants', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacp.org/resource/new-investigator-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacpdm.org/professional-opportunities/grants', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacpdm.org/professional-opportunities/awards', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/aacr-bayer-innovation-and-discovery-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/aacr-bms-midcareer-female-investigator-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/independent-research-grants/aacr-debbies-dream-foundation-innovation-and-discovery-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/aacr-novocure-tumor-treating-fields-research-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/aacr-plga-fund-at-the-pbtf-research-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/independent-research-grants/aacr-mark-foundation-for-cancer-research-science-of-the-patient-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/independent-research-grants/lustgarten-foundation-swim-across-america-aacr-pancreatic-cancer-early-detection-research-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/neuroendocrine-tumor-research-foundation-aacr-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/independent-research-grants/victorias-secret-global-fund-for-womens-cancers-rising-innovator-research-grant-in-partnership-with-pelotonia-aacr/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/independent-research-grants/aacr-johnson-and-johnson-science-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/independent-research-grants/pancreatic-cancer-action-network-aacr-research-acceleration-network-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/independent-research-grants/pancreatic-cancer-collective/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.aacr.org/professionals/research-funding/funded-research/independent-research-grants/su2c-catalyst-project/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES ('https://www.icebenfund.com/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.ice.org.uk/engineering-resources/our-services/ice-benevolent-fund', '2024-04-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.ies.org/membership/grants-scholarships/howard-brandston-student-lighting-design-education-grant/', '2024-05-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.ies.org/membership/grants-scholarships/leadership-forum-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.istructe.org/training-and-development/apply-for-grants/msc-research-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.istructe.org/training-and-development/apply-for-grants/research-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.nae.edu/20683.aspx', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://canadacouncil.ca/funding/grants/explore-and-create/professional-development-for-artists', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://canadacouncil.ca/funding/grants/explore-and-create/research-and-creation', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.nae.edu/20681/DraperPrize#tabs', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.nae.edu/20685.aspx', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.nae.edu/216559.aspx', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://canadacouncil.ca/funding/grants/explore-and-create/concept-to-realization', '2024-04-17');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.nationalacademies.org/our-work/arab-american-frontiers-of-science-engineering-and-medicine', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://canadacouncil.ca/funding/grants/explore-and-create/artist-driven-organizations', '2025-03-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://canadacouncil.ca/funding/grants/engage-and-sustain/artistic-catalysts', '2024-01-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://new.nsf.gov/funding/opportunities/research-science-technology-enterprise-indicators', '2025-01-21');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://canadacouncil.ca/funding/grants/supporting-artistic-practice/sector-innovation-and-development', '2024-10-16');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.nibib.nih.gov/research-program/c3i-program', '2024-04-24');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://canadacouncil.ca/funding/grants/supporting-artistic-practice/professional-development-for-arts-professionals', '2024-06-12');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://canadacouncil.ca/funding/grants/supporting-artistic-practice/literary-publishing-projects', '2024-05-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://canadacouncil.ca/funding/grants/supporting-artistic-practice/support-organizations', '2026-01-21');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://canadacouncil.ca/funding/grants/supporting-artistic-practice/national-arts-service-organizations', '2026-01-21');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://serb.gov.in/page/english/research_grants#Core%20Research%20Grant%20(CRG)', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.uefoundation.org/uef-grants-program/', '2024-08-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.ainse.edu.au/postgraduate/', '2024-04-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.asabe.org/Awards-Competitions/Grants/Initiative-Fund', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.asabe.org/GivingBack', '2024-12-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.atse.org.au/programs-and-awards/global-science-technology-diplomacy-fund-strategic-element/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.atse.org.au/programs-and-awards/awards/batterham-medal/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.atse.org.au/programs-and-awards/awards/david-and-valerie-solomon-award/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.atse.org.au/programs-and-awards/awards/icm-agrifood-awards/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.bmes.org/career-development-awards', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.eifgrants.org/how-to-apply', '2024-08-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://humanitiesdc.org/grant-opportunities/capacity-building/', '2024-05-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://humanitiesiowa.org/grants/apply-for-a-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.humanitieskansas.org/grants-programs/action-grants', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.humanitieskansas.org/grants-programs/humanities-for-all-grants', '2024-09-23');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.humanitieskansas.org/grants-programs/culture-preservation-grants', '2024-09-23');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.humanitiesmontana.org/mini-grants/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.humanitiestexas.org/grants/apply', '2024-09-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.humboldt-foundation.de/en/apply/sponsorship-programmes/alexander-von-humboldt-professorship', '2024-09-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://huntington.org/available-fellowships', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://huttonfoundation.org/funding-general-guidelines/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://hydefoundation.org/grants/apply/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://hands.hydroassoc.org/2024-innovator-award/', '2024-06-12');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://hands.hydroassoc.org/2024-accelerator-award/', '2024-06-12');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://hands.hydroassoc.org/travel-award/', '2024-04-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aadocr.org/awards/mind/aadocr-mind-future-mentee-application', '2024-05-10');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aadocr.org/awards/aadocr-bloc-travel-grant', '2024-10-22');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aadocr.org/awards/aadocr-hatton-competition', '2024-10-22');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aadocr.org/awards/aadocrcadr-joseph-lister-award-new-investigators', '2024-10-22');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.aadocr.org/awards/aadocr-student-research-day-award', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.iaf.gov/apply-for-grant/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.ianpotter.org.au/can-we-apply/can-we-apply-university/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.ianpotterculturaltrust.org.au/opportunities/emerging-artist-grants/how-to-apply/', '2024-06-18');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://iars.org/iars-mentored-research-award/', '2024-04-30');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.icms.org.uk/funding-opportunities/ke-event-fund', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.icms.org.uk/funding-opportunities/ke-follow-fund', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.icrg.org/information/apply-for-icrg-funding', '2024-06-24');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://icrofs.dk/en/translate-to-english-soeg-forskningsmidler/translate-to-english-organic-rdd-forskningsmidler', '2024-05-06');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://ics.ac.uk/research/grants-and-awards.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://ictr.wisc.edu/funding-opportunities-2/', '2024-05-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.icwa.org/apply/', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.idahospacegrant.org/grant', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://idrc-crdi.ca/en/funding/applying-funding', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://ielts.org/researchers/funding-and-awards/research-funding', '2024-06-30');

INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.calgary.ca/social-services/funding/home-program-grants.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.alberta.ca/watercourse-crossing-program', '2024-10-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.cheminst.ca/wp-content/uploads/2023/04/CSChE-D.-G.-Fisher-Award-Terms-of-Reference-04032023-1.pdf', '2024-12-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://engineerscanada.ca/awards-and-honours/scholarships/graduate/engineers-canada-manulife-scholarship', '2024-10-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.sshrc-crsh.gc.ca/funding-financement/nfrf-fnfr/transformation/2024/competition-concours-eng.aspx', '2024-09-05');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.nserc-crsng.gc.ca/Prizes-Prix/McDonald-McDonald/Index-Index_eng.asp', '2024-12-16');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.nserc-crsng.gc.ca/Prizes-Prix/Strickland-Strickland/About-Apropos_eng.asp', '2024-11-28');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.nserc-crsng.gc.ca/Prizes-Prix/Herzberg-Herzberg/About-Apropos_eng.asp', '2024-11-28');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.rsf-fsr.gc.ca/home-accueil-eng.aspx', '2024-05-21');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.researchnet-recherchenet.ca/rnr16/vwOpprtntyDtls.do?prog=4025&view=currentOpps&org=CIHR&type=EXACT&resultCount=25&sort=program&next=1&all=1&masterList=true', '2024-10-22');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://open.alberta.ca/publications/ahrf-heritage-preservation-partnership-program-guidelines-grants-for-heritage-awareness-projects#summary', '2025-02-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.canada.ca/en/department-national-defence/programs/minds/targeted-engagement-grant.html', '2024-04-03');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://mitsloan.mit.edu/faculty/academic-groups/applied-economics/about-us', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.neh.gov/program/archaeological-and-ethnographic-field-research', '2024-07-17');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://idsafoundation.org/alz-research-grant/', '2024-08-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://foundation.asrt.org/what-we-do/research-grants/research-grants', '2024-05-23');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.ualberta.ca/radiology-and-diagnostic-imaging/about-the-department/the-radiology-endowed-fund.html', '9999-01-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://grants.nih.gov/grants/guide/pa-files/PAR-22-047.html', '2024-11-05');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://grants.nih.gov/grants/guide/pa-files/PAR-22-093.html', '2024-11-12');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://calgaryartsdevelopment.com/grant-investment-programs/programs/all/project-grant-program-individuals-collectives/', '2024-05-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.researchnet-recherchenet.ca/rnr16/vwOpprtntyDtls.do?prog=4105&view=currentOpps&org=CIHR&type=EXACT&resultCount=25&sort=program&next=1&all=1&masterList=true', '2024-07-09');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.researchnet-recherchenet.ca/rnr16/vwOpprtntyDtls.do?prog=4109&view=currentOpps&org=CIHR&type=EXACT&resultCount=25&sort=program&next=1&all=1&masterList=true', '2024-09-24');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.researchnet-recherchenet.ca/rnr16/vwOpprtntyDtls.do?prog=4073&view=currentOpps&org=CIHR&type=EXACT&resultCount=25&sort=program&next=1&all=1&masterList=true', '2024-06-25');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.researchnet-recherchenet.ca/rnr16/vwOpprtntyDtls.do?prog=4055&view=currentOpps&org=CIHR&type=EXACT&resultCount=25&sort=program&next=1&all=1&masterList=true', '2024-05-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.researchnet-recherchenet.ca/rnr16/vwOpprtntyDtls.do?prog=4072&view=currentOpps&org=CIHR&type=EXACT&resultCount=25&sort=program&next=1&all=1&masterList=true', '2024-04-22');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://datascience.uchicago.edu/research/research-funding/ai-science-research-funding-opportunities/', '2024-04-10');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.mentorworks.ca/government-funding/research-development/agricultural-clean-technology-program/#eligible-applicants', '2028-03-31');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://cleancompetition.org/programs/grants-program/', '2024-08-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.sshrc-crsh.gc.ca/funding-financement/programs-programmes/partnership_engage_grants-subventions_d_engagement_partenarial-eng.aspx', '2024-05-22');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.sshrc-crsh.gc.ca/funding-financement/programs-programmes/connection_grants-subventions_connexion-eng.aspx', '2024-05-01');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://healthresearchbc.ca/fundingprogram/reach-program/', '2024-05-13');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.queensu.ca/urs/funding/opportunity-details/?id=5816', '2024-05-13');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://new.nsf.gov/funding/opportunities/global-centers-gc/nsf24-556/solicitation', '2024-06-11');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.td.com/ca/en/about-td/ready-commitment/funding/fef-grant', '2024-07-15');
INSERT INTO url_db.funding_opportunity_urls(url, closeDate) VALUES('https://www.rbc.com/community-social-impact/climate/environmental-donations/index.html', '2024-05-06');


CREATE TABLE url_db.researcher_profiles_urls(
	id int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    url varchar(500) NOT NULL,
	email varchar(500) NOT NULL,
	UNIQUE (email)
);

CREATE TABLE url_db.users(
	id int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username varchar(500) NOT NULL,
	password varchar(500),
	salt varchar(500),
	UNIQUE (username)
);
